(module $provider
  (type $int (func (result i32)))
  (table 1 funcref)
  (func (result i32) i32.const 900)
  (func (export "accept") (param funcref) (result i32)
    i32.const 0 local.get 0 table.set
    i32.const 0 call_indirect (type $int))
  (func $target (result i32) i32.const 902)
  (func $get (export "get") (result funcref) ref.func $target)
  (func (export "get_pair") (result funcref i32) ref.func $target i32.const 17)
  (func (export "get_tail") (result funcref) return_call $get)
  (func (export "get_null") (result funcref) ref.null func)
  (elem declare func $target))
(register "provider" $provider)
(module $caller
  (import "provider" "accept" (func $accept (param funcref) (result i32)))
  (import "provider" "get" (func $get (result funcref)))
  (import "provider" "get_pair" (func $get_pair (result funcref i32)))
  (import "provider" "get_tail" (func $get_tail (result funcref)))
  (import "provider" "get_null" (func $get_null (result funcref)))
  (type $int (func (result i32)))
  (func $local (result i32) i32.const 42)
  (elem declare func $local)
  (table 1 funcref)
  (func (export "argument") (result i32) ref.func $local call $accept)
  (func (export "tail_argument") (result i32) ref.func $local return_call $accept)
  (func (export "null") (result i32) call $get_null ref.is_null)
  (func (export "multi_result") (result i32) (local i32)
    i32.const 0 call $get_pair local.set 0 table.set
    i32.const 0 call_indirect (type $int) local.get 0 i32.add)
  (func (export "tail_result") (result i32)
    i32.const 0 call $get_tail table.set
    i32.const 0 call_indirect (type $int))
  (func (export "returned") (result i32)
    i32.const 0 call $get table.set
    i32.const 0 call_indirect (type $int)))
(assert_return (invoke $caller "argument") (i32.const 42))
(assert_return (invoke $caller "returned") (i32.const 902))
(assert_return (invoke $caller "tail_argument") (i32.const 42))
(assert_return (invoke $caller "multi_result") (i32.const 919))
(assert_return (invoke $caller "tail_result") (i32.const 902))
(assert_return (invoke $caller "null") (i32.const 1))
