#pragma once

typedef enum {
	/* System Throw */
	ERR_FILENOTOPEN = 100,
	ERR_HEADERNOTDETECT = 101,
	ERR_VERSIONMISMATCH = 102,
	ERR_MAGICNOTDETECT = 103,
	ERR_FUNCTION_COUNT_MISSMATCH = 104,
	ERR_TOO_MANY_LOCALS = 105,
	ERR_NOTOPEND = 106,
	ERR_ZEROBYTEEXPECTED = 107,
	ERR_DATASECTIONREQUIRED = 108,
	ERR_UNKNOWN_IMPORT_KIND = 109,
	ERR_MALFORMED_MUTABILITY = 110,
	ERR_MALFORMED_REFERENCE_TYPE = 111,
	ERR_MISMATCH_SECTION_SIZE = 112,
	ERR_STACK_OVERFLOW = 113,
	ERR_TRAP_UNREACHABLE = 114,
	ERR_TRAP_UNDEFINED_ELEMENT = 115,
	ERR_TRAP_UNINITIALIZED_ELEMENT = 116,
	ERR_TRAP_INDIRECT_CALL_TYPE_MISMATCH = 117,
	ERR_TRAP_OUT_OF_BOUNDS_TABLE_ACCESS = 118,
	ERR_TRAP_OUT_OF_BOUNDS_MEMORY_ACCESS = 119,
	ERR_TRAP_INTERGER_DIVIDE_BY_ZERO = 120,
	ERR_TRAP_INTERGET_OVERFLOW = 121,
	ERR_TRAP_INVALID_CONVERSION_TO_INTERGER = 122,
	ERR_NOTMODULEINIT = 123,
	ERR_UNKNOWN_IMPORT = 124,
	ERR_INCOMPATIBLE_IMPORT_TYPE = 125,
	ERR_INVALID_FUNC_PARAM = 126,
	ERR_UNKNOWN_IMPORT_SYMBOL = 127,
	ERR_OUTOFFUNCTION_TABLE = 128,
	ERR_NOT_RESUME = 129,
	ERR_FUNCTION_ALREADY_SUSPENDED = 130,
	ERR_MALFORMED_LOCALVAL = 131,
	ERR_MALFORMED_BLOCK = 132,
	ERR_MALFORMED_FUNC = 133,
	ERR_MALFORMED_TABLE = 134,
	ERR_MALFORMED_0XFC = 135,
	ERR_MALFORMED_GLOBAL = 136,
	ERR_MALFORMED_STORE = 137,
	ERR_MALFORMED_MEMORY = 138,
	ERR_TYPE_MISMATCH = 139,
	ERR_MALFORMED_ALIGN = 140,
	ERR_MALFORMED_UTF8 = 141,
	ERR_MALFORMED_LANE = 142,
	/* WASM 3.0 threads: atomic.wait は shared でない memory 上では trap */
	ERR_ATOMIC_WAIT_NON_SHARED = 143,
	/* atomic load/store/rmw のアラインメント不一致 trap */
	ERR_TRAP_UNALIGNED_ATOMIC = 144,
	/* WASM 3.0 exception handling: throw された例外がキャッチされなかった */
	ERR_TRAP_UNCAUGHT_EXCEPTION = 145,
	/* WASM exception が throw され、どの try/catch にも捕捉されないまま
	 * 関数外へ伝播した (core エンジンの trap "wasm exception" / "null exnref")。 */
	ERR_WASM_EXCEPTION = 146,
	/* features.h で OFF にされた WASM 機能 (SIMD / Threads 等) を含む
	 * モジュールを load しようとした。 */
	ERR_FEATURE_DISABLED = 147,
} kinowasm_errorcode_t;
